### ISSUE TITLE
Hi! Jakub

### ISSUE THREAD

**Issue by thris00** [Kjplay/Twine-Harlowe-Save-To_File#2]
I just want to say how useful this 'save to file code' to me, I've already used in my stury, thanks very much!

But for the  README part, I think it is a little cunfusing for that you describe  A (savetofile: String, String) macro

"
It takes 2 arguments
slotName - string containing your slot name. The same as you would use for (load-game:) or (save-game:) macro.
fileName - string containing your file name, without extension for example my_save
"
it made me think  it means  (savetofile: slotName, fileName ) 
but later I figured out it is actually  (savetofile: fileName, slotName ) 

So I can pull off my saves into local, however, I don't understand how to use  (loadfromfile: String [, ...String]) 
I tried (loadfromfile:  fileName,  slotName) and many other combination ,but it didn't work.

Could you help specify the detail of how to use it? 

Thanks again :)

**Comment by Kajot-dev** [comment]
Hi! The library is pretty outdated, given, that the Harlowe 3.2.3 has released, but I'll do my best!
1. Yes, you are correct `(savetofile:)` takes filename and then slotName
2. About `(loadfromfile:)`
So you probably know, that in Harlowe you can have multiple save slots and that carries onto the save files. `(loadfromfile:)` opens a pop-up window, where you can select a file, that you want, so you **don't provide the filename at all** as browser does not have direct access to the user's filesystem
I'll provide a few examples
 - `(loadfromfile: "Slot A")` will only accept files with saveslot "Slot A" and will load the file's contents  into that saveslot
 - `(loadfromfile: "Slot A", "Slot B")` will ONLY accept files with saveslot "Slot B", BUT will load file's contents into the "Slot A"
 - `(loadfromfile: "Slot A", "Slot A", "Slot B")` will accept files with EITHER saveslot "Slot A" or "Slot B", but will load the file's contents to the "Slot A"
 
It's important to understand, because it will OVERWIRTE the "Slot A" (first argument) saveslot, so the game data saved with `(save-game: "Slot A")` will be replaced by the data found in the file
 
 If you have any questions, feel free to ask!

**Comment by Kajot-dev** [comment]
There seems to be no response, so I'm closing it.
